/*
 * LES DESSINS EN PIXELS du menu principal, façon console 16 bits : l'icône de chaque tour (32 × 32),
 * l'écrou ⚙ des réglages (24 × 24) et la main qui montre la tuile touchée.
 *
 * Chaque dessin est une grille de caractères, un par pixel : une lettre de la palette, ou « . »
 * pour un pixel vide. src/pixel.ts en fait un SVG de carrés, net à toutes les tailles.
 *
 * Les icônes et l'écrou sont ENGENDRÉS par outils/icones-16-bits.py (éclairage des volumes,
 * tramage des ombres, comme sur les consoles 16 bits) : pour les changer, modifier le script et
 * recopier sa sortie ici. Les tests (tests/logic/pixels.test.ts) vérifient la taille des grilles,
 * les couleurs, et que l'écrou est parfaitement symétrique, son trou au centre.
 */

/** La palette des dessins : une lettre par couleur. */
export const PALETTE: Readonly<Record<string, string>> = {
	a: '#0d0a1c',
	b: '#45258a',
	c: '#2e1863',
	d: '#1c0f3d',
	e: '#6538ad',
	f: '#d9c8f2',
	g: '#ffffff',
	h: '#0e0820',
	i: '#fff0b0',
	j: '#f2c55c',
	k: '#c98c2e',
	l: '#8f5a1c',
	m: '#5a3410',
	n: '#2a1606',
	o: '#7d4c16',
	p: '#b37a26',
	q: '#4e2c0c',
	r: '#e0aa44',
	s: '#fff4c4',
	t: '#f8d778',
	u: '#160a10',
	v: '#e6dcc4',
	w: '#fbf6ea',
	x: '#b13e53',
	y: '#7a1c2c',
	z: '#1c2743',
	A: '#0b0b12',
	B: '#d8e0ee',
	C: '#b0520f',
	D: '#f7931e',
	E: '#ffc46b',
	F: '#6b2a0a',
	G: '#9aa6bd',
	H: '#3a2208',
	// La main : contour, blanc, ombre grise.
	1: '#0b0b12',
	2: '#ffffff',
	3: '#c6cfe0',
};

/** Taille des icônes des tours, en pixels. */
export const TAILLE = 32;

/** Taille de l'écrou, en pixels. */
export const TAILLE_ECROU = 24;

/** L'icône de chaque tour, par dossier (content/tours.ts). */
export const ICONES: Readonly<Record<string, readonly string[]>> = {
	'boule-de-cristal': [
		'................................',
		'............aaaaaaaa............',
		'..........aabbbcbccdaa..........',
		'.........abbbbbbccccdda.........',
		'........abebebbbbcbcccda........',
		'.......abefffbcbcbcbccdda.......',
		'......abefgggfbbbbbbbccdda......',
		'.....abbbggggfcbcbbbccddhha.....',
		'.....abbefgggfbbbbbbbccddha.....',
		'....abbbbfggfbcbbebbccddhhha....',
		'....acbbbbbbbcbbebebbdchhhha....',
		'....abbbcbcbcbbebebbcdhhhhha....',
		'....acbbbcbcbbebebbccddhhhha....',
		'....accbcbcccbbebbccddhhhhha....',
		'....acccccbcbbebbccddhhhhhha....',
		'....acdcdccbcbbbccddhhhhhhha....',
		'....adcdccccbbbcbcdhdhhhdhha....',
		'.....adddcdccbccddhhhhhhhha.....',
		'.....addddcccccddhhhhhhhhha.....',
		'......adhddcddddhhhhhhhhha......',
		'.......adddddddhdhhhhhhha.......',
		'........ahhhhdhhhhhhhhha........',
		'.........ahhhhhhhhhhhha.........',
		'..........aaiijjkkllaa..........',
		'..........aiiiijjkklla..........',
		'...........aaiijkklaa...........',
		'............aiijjkka............',
		'.........aaaaiiikklaaaa.........',
		'........aiiiijjkjkklllla........',
		'.......aiiiijjkjkklkllmma.......',
		'......aiiiijijjkjkklkllmla......',
		'.......aaaaaaaaaaaaaaaaaa.......',
	],
	'pile-ou-face': [
		'................................',
		'................................',
		'............nnn..nnn............',
		'..........nnooonnpopnn..........',
		'........nnoopopopoppppnn........',
		'.......nooooooooqpopppppn.......',
		'......nooooooooooooooprprn......',
		'......noooqsrtrtrrrrsopppn......',
		'.....nnoootttttrtrtrtroprnn.....',
		'....noooqtrtrtrtrtrrrrroprpn....',
		'...noopotrtrtrtrtrtrrrrrorrrn...',
		'...nooqortrtrrrrrrrrrrrrqorrn...',
		'..nopootttsstrtrtrsstrrrrorrtn..',
		'..noopqtrsoostrrrsoosrprrorrrn..',
		'..nopoortotrortrrorrorrrrotrtn..',
		'..npooqtrrrsorrrrorrorprpoqtrn..',
		'..noposrtrsotrrrtorrorrrrsortn..',
		'..npopqtrsorrrrrroprorprportrn..',
		'...npportosssrrrrossoprrrottn...',
		'...nopqrroooorrrprooprprportn...',
		'...nppootrrrtrrrrrrrrrrpoottn...',
		'...nppporrrrrrprrrprprprqtrtn...',
		'....nprporrrrrrrrprrrprotttn....',
		'....npprporrprprprprppqttttn....',
		'.....nrprrosrrrrrrrpsottttn.....',
		'......nrrrroqoqoqoqoqttttn......',
		'.......nrrrrtrtootttttttn.......',
		'........nnnrrrrtrtrtrnnn........',
		'...........ntrtrttttn...........',
		'............nnnnnnnn............',
		'................................',
		'................................',
	],
	'six-predictions': [
		'................................',
		'................................',
		'................................',
		'.........uuuuuuuuuuuu...........',
		'........uvvvvvvvvvvvvu..........',
		'...uuuuuvwwwwwwwwwwwwvu.........',
		'..uvvvvvvwjxxxjxxxjxwvuuuuuuu...',
		'.uvwwwwwvwxjxjxjvwvwvvvvvvvvvu..',
		'.uvwjxxxvwxxjxxwwwwvwvwvwvvvvvu.',
		'.uvwxjxjvwxjxjxwvwvwvwvvvvvvvvu.',
		'.uvwxxjxvwjxxxjwwvwvwvwvwvwvvvu.',
		'.uvwyjxjvwyjyjywvwzwzzzzvzzvvvu.',
		'.uvwjxxxvwxxjxxwwwwvwvwvwvvvvvu.',
		'.uvwxjyjvwyjyjywvwvwvwvvvvvvvvu.',
		'.uvwxxjxvwjxxyjwwvzzzvzzzvwvvvu.',
		'.uvwyjyjvwyjyjywvwvwvvvvvvvvvvu.',
		'.uvwjxxyvwxyjyxwwwwvwvwvwvvvvvu.',
		'.uvwyjyjvwyjyjywvwvwvwvvvvvvvvu.',
		'.uvwxyjyvwjyxyjwwvwvwvwvwvwvvvu.',
		'.uvwyjyjvwyjyjywvwvwvvvvvvvvvvu.',
		'.uvwjyxyvwxyjyxwwwwzwzzzzvzvvvu.',
		'.uvwyjyjvwyjyjywvwvwzzzzvzvvvvu.',
		'.uvwxyjyvwwwwwwwwvwvwvwvwvwvvvu.',
		'.uvwyjyjyvvvvvvwvwvwvvvvvvvvvvu.',
		'.uvwwwwwwwwwwwwwwwwvwvwvwvvvvvu.',
		'..uvvvvvvvvvvvvwvwvwvwvvvvvvvvu.',
		'...uuuuuuuuuuuuwwvwvwvwvwvwvvvu.',
		'..............uwvwvwvvvvvvvvvvu.',
		'...............uwwwvwvwvwvvvvu..',
		'................uuuuuuuuuuuuu...',
		'................................',
		'................................',
	],
	'analyseur-q': [
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'...............AA...............',
		'..............AggA.AAAAAAA......',
		'..............AgBAACCDCDCDAA....',
		'.............AggggCCAAAAADEDA...',
		'............AgBgBgBA.....AAEA...',
		'..........AAgggggBgBA.....AEA...',
		'.........AFFBgBgBBBBAA....AEA...',
		'........AFgggggBgBgBBBA...AEA...',
		'.......AFgggBgBgBBBBBBGA..AEA...',
		'......AFgggggBgBgBBBBGBGAAEEA...',
		'.....AFFggBgBgBBBBBBGBGBAEDA....',
		'....AFFAgggBgBgBgBBBBBBGEEA.....',
		'...AFFAAggBgBgBBBBGBGBGEDA......',
		'...AFA..ABgBgBgBBBBBBGEDA.......',
		'...AFA...ABgBBABGAGBGDDA........',
		'...AFA....AAAAABBAADEDA.........',
		'...AFA.......ABBGDDDAA..........',
		'...AFAA.....ABBDDDBA............',
		'...AFCFAAAAACDCDGGGGA...........',
		'....AACCCCDCDAAAAAAA............',
		'......AAAAAAA...................',
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
	],
};

/**
 * L'écrou ⚙ des réglages : huit dents autour d'un trou rond, au centre exact de la grille, en
 * anneaux de lumière (sombre au bord du trou, clair au milieu, dents plus sombres). Calculé pour
 * être symétrique dans tous les sens.
 */
export const ECROU: readonly string[] = [
	'........HkkkkkkH........',
	'.....HH.HkkkkkkH.HH.....',
	'....HkkHHkkkkkkHHkkH....',
	'...HkkkH.HkkkkH.HkkkH...',
	'..HkkkkkHjjjjjjHkkkkkH..',
	'.HkkkkkjjjjiijjjjkkkkkH.',
	'.HkkkkjjiiiiiiiijjkkkkH.',
	'..HHkjjiiiiiiiiiijjkHH..',
	'HHH.HjiiilllllliiijH.HHH',
	'kkkHjjiillHHHHlliijjHkkk',
	'kkkkjjiilH....Hliijjkkkk',
	'kkkkjiiilH....Hliiijkkkk',
	'kkkkjiiilH....Hliiijkkkk',
	'kkkkjjiilH....Hliijjkkkk',
	'kkkHjjiillHHHHlliijjHkkk',
	'HHH.HjiiilllllliiijH.HHH',
	'..HHkjjiiiiiiiiiijjkHH..',
	'.HkkkkjjiiiiiiiijjkkkkH.',
	'.HkkkkkjjjjiijjjjkkkkkH.',
	'..HkkkkkHjjjjjjHkkkkkH..',
	'...HkkkH.HkkkkH.HkkkH...',
	'....HkkHHkkkkkkHHkkH....',
	'.....HH.HkkkkkkH.HH.....',
	'........HkkkkkkH........',
];

/** La main des menus de jeux de rôle 16 bits, qui montre la tuile touchée. */
export const MAIN: readonly string[] = [
	'................',
	'...11111........',
	'..1222221111111.',
	'..12222222222221',
	'..1222221111111.',
	'.132222221......',
	'.1322222221.....',
	'.133222221......',
	'..13332221......',
	'...1133321......',
	'.....1111.......',
	'................',
];
